#!/usr/bin/env python
# coding: utf-8


pip install vadersentiment
pip install SpeechRecognition
pip install pocketsphinx

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import speech_recognition as sr

AUDIO_FILE = "AHJD2.wav"

r = sr.Recognizer()
with sr.AudioFile(AUDIO_FILE) as source:
    audio = r.record(source)  # read the entire audio file

try:
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))


#Or 

# recognize speech using Google Speech Recognition
try:
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio))
except sr.UnknownValueError:
    print("Google Speech Recognition could not understand audio")
except sr.RequestError as e:
    print("Could not request results from Google Speech Recognition service; {0}".format(e))


# # Sentiment Analysis

Sentence =[str(r.recognize_sphinx(audio))]
analyser = SentimentIntensityAnalyzer()
for x in Sentence:
    a= analyser.polarity_scores(x)
    print(a)




